[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "sidesched"
version = "0.0.1"
requires-python = ">=3.7"

[project.optional-dependencies]
dev = ["pytest ~= 7.1.3"]
